language: java
jdk: oraclejdk8
script: "./gradlew build"
deploy:
  provider: releases
  api_key:
    secure: aN0tvJOFCNT7SmPJWHMYDDUCFYEYuSHfcwTPttSifGtbuwVlXBEVpqiLgVX5+dEQdvbG9lVRb4XuZ4AkCKeG2T55P0BDZRBW8dhEQfXh9M1PTeM96NpUC2mNXoENFXh/b8JKpT59B8uNmly4xB1BQ/ltsEIxzTtaMa3ryGsQ8BqUwRUvciE0kjC2Xebb2H2Km+mwjhHZQhFbDr+FstMDLc/dm4KSpUM2X94UTDVkyMyc3zL5IwH/cViGLfuJ9UnEdIStHIAZx3leBC0MkKRZwyYBTzd2tuHi10sXhbVnpqT+DUtWxlysSjn9bU6TPKoYoraYj0gxq3BwCRYGh7mssw7oEvOndfypEzqIPq3YEMrqHtnmcj9SNQsyBaVGNgvfjtTHFkNof6YIM7yMFOcw1CvZ+FQgaVZ5t/hLgQhAw4NALOFEQhbZWyZRL52z+UNZMwgf/ANjEahaypavAThMzy2wQqB0hrg7NsEEtHJXovtrOUAUoT//R4FeWImuxIcsdNM4nbFC7qs1UlM3XtBjMshozvMMsC1IWvHg4mJtctcOWWfvDAZ1g/Dh857YGt2Mz+Iervup2/XL0L2qZSYE8OuGL2zPcG79JcSrT/bPI+zW+FXwkCkTnlI7qXGF2cu6TmHamoY+Tb105Y3HtkIAcaJdX6BOSl/sJzJvLl/ZRdg=
  file: build/libs/mc-properties-1.0.jar
  skip_cleanup: true
  on:
    repo: r4v3n6101/mc-properties
    tags: true
    branches:
      only:
        - master